services:
  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    restart: always
    volumes:
      - ./config/dashboard-config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    ports:
      - "9000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./config/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./plugins/apisix/plugins:/usr/local/apisix/plugins:ro
      - ./logs:/usr/local/apisix/logs
      - /tmp:/tmp
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9180:9180"
    networks:
      apisix:

  go-plugin-runner:
    build:
      context: ./go-plugin-runner
      dockerfile: Dockerfile.go-plugin
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      - APISIX_LISTEN_ADDRESS=unix:/tmp/runner.sock
    networks:
      apisix:
    command: ["/usr/local/bin/go-plugin-runner"]

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    restart: always
    volumes:
      - etcd_data:/etcd-data
    environment:
      ETCD_NAME: "etcd-server"
      ETCD_DATA_DIR: "/etcd-data"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd:2380"
      ETCD_INITIAL_CLUSTER: "etcd-server=http://etcd:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      apisix:
    command: etcd

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local