#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apisix:
  extra_lua_path: "/usr/local/apisix/plugins/?.lua"
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false
  config_center: etcd # Using etcd for configuration
  enable_debug: true             # Enable debug mode for detailed logging
  enable_dev_mode: true          # Enable development mode
  admin_listen:
    ip: 0.0.0.0
    port: 9180

# Logging configuration for debugging
nginx_config:
  error_log: "/usr/local/apisix/logs/error.log"
  error_log_level: "debug"          # Can be: debug, info, notice, warn, error, crit
  access_log: "/usr/local/apisix/logs/access.log"
  access_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time "$upstream_addr" "$upstream_status" "$request_id"'
  access_log_format_escape: default

# External plugin configuration for Go plugin runner  
ext-plugin:
  path_for_test: /tmp/runner.sock

plugins:
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  # - dubbo-proxy
  - echo
  - custom-header
  - error-log-logger
  # - example-plugin
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  - log-rotate
  - node-status
  - openid-connect
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  - skywalking
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - server-info
  - traffic-split
  # External plugins (Go Plugin Runner)
  - ext-plugin-pre-req
  - ext-plugin-post-req
  - ext-plugin-post-resp
  # Custom Lua plugins (kept for reference)
  - hello-world
  - response-transformer
  
plugin_attr:
  upstream-response-transformer:
    # Enable both header_filter and body_filter phases
    phase: [ "header_filter", "body_filter" ]
  opentelemetry:
    # trace_id_source: x-instance-id - Source of the trace ID. Valid values are random or x-request-id. When set to x-request-id, the value of the x-request-id header will be used as trace ID. Make sure that it matches the regex pattern [0-9a-f]{32}.
    resource:
      service.name: APISIX-DMZ         #3
    collector:
      #4  address: jaeger:4318         #4
      address: http://172.20.0.1:5080/api/default
      request_headers:              # Set the headers to include in requests to the OpenTelemetry collector.
        Authorization: Basic cm9vdEByb290LmNvbTp1aFJVNUVjZ1dLZDZzZUtk 

global_rules:
  - id: 1
    plugins:
      opentelemetry:
        sampler:
          name: always_on          #1
    
deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds